# user-service

version: '3.8'

services:
  temporal-service:
    image: node:19.0.0-alpine
    container_name: temporal-service
    user: node
    working_dir: /home/node
    tty: true
    stdin_open: true
    env_file:
      - .temporal-service.env
    ports:
      - "3003:3000"
    volumes:
      - .:/home/node
      - ../libs:/home/node/libs

  temporal-service-db:
    image: postgres:15-alpine3.16
    container_name: temporal-service-db
    restart: always
    env_file:
      - .temporal-service.env
    environment:
      POSTGRES_PASSWORD: ${TEMPORAL_SERVICE_PASSWORD}
      POSTGRES_HOST: ${TEMPORAL_SERVICE_HOST}
      POSTGRES_PORT: ${TEMPORAL_SERVICE_PORT}
      POSTGRES_USER: ${TEMPORAL_SERVICE_USER}
      POSTGRES_DB: ${TEMPORAL_SERVICE_DB}
    ports:
      - "5433:5433"
    volumes:
      - temporal-db:/data/db

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  temporal-db:

networks:
  default:
    name: microservices-network
    external: true